# Ensure runtime and state directories exist.
#
# Syntax: https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html
#
# Type Path                Mode UID  GID      Age Argument

d /run/sourceos            0755 root root     -   -
d /var/lib/sourceos        0755 root root     -   -
d /var/lib/sourceos/gate   0755 root root     -   -
d /var/lib/sourceos/gate/egress 0755 root root -   -
d /var/lib/sourceos/audit  0755 root root     -   -
