# Create the 'sourceos' group used for unix socket access control.
#
# Syntax: https://www.freedesktop.org/software/systemd/man/sysusers.d.html
#
# Type Name     ID  GECOS                   Home Shell
# g    groupname

g sourceos -
